export type {
  ColorScheme,
  DeepPartial,
  DensityName,
  ElevationName,
  FocusRingGeometry,
  InteractionToneColors,
  MotionName,
  MotionRecord,
  Palette,
  PaletteScale,
  PaletteStep,
  RadiusName,
  SemanticTokens,
  ShadowLayer,
  SpaceStep,
  Theme,
  ToneName,
  TypographyRecord,
  TypographyRole,
} from './types.js';

export {
  blueScale,
  blueScaleDark,
  defaultPalette,
  defaultPaletteDark,
  grayScale,
  grayScaleDark,
  greenScale,
  greenScaleDark,
  redScale,
  redScaleDark,
} from './palette.js';

export {
  compactSpace,
  defaultFocusRing,
  defaultMotion,
  defaultRadius,
  defaultShadow,
  defaultSpace,
  defaultTypography,
  motionNames,
  sharedSemanticScales,
  spaceSteps,
  spaceVariantSteps,
  toneNames,
} from './scales.js';
